changelog-seen        = 1
profile               = <none>

[llvm]
link-shared           = true

[build]
doc-stage             = 0
build-stage           = 1
test-stage            = 1
dist-stage            = 2
install-stage         = 2
bench-stage           = 2

build                 = 'x86_64-apathy-linux-musl'
host                  = ['x86_64-apathy-linux-musl']
target                = ['x86_64-apathy-linux-musl']

cargo                 = '/opt/rustc-1.48.0/bin/cargo'
rustc                 = '/opt/rustc-1.48.0/bin/rustc'
python                = 'python3'

extended              = true
tools                 = ['cargo']

local-rebuild         = true
low-priority          = false
full-bootstrap        = false
print-step-timings    = false
verbose               = 0

docs                  = false
compiler-docs         = false
submodules            = false
locked-deps           = true
vendor                = true
sanitizers            = false
profiler              = false
cargo-native-static   = false

[install]
prefix                = '/opt/rustc-1.48.0'

[rust]
channel               = 'nightly'

optimize              = true
codegen-units         = 16
codegen-units-std     = 1
backtrace             = false
incremental           = false
parallel-compiler     = false

default-linker        = 'clang'
llvm-libunwind        = true
llvm-tools            = true
lld                   = false
use-lld               = false

rpath                 = false
codegen-tests         = false
deny-warnings         = true
jemalloc              = false

debug                 = false
debug-assertions      = false
debug-assertions-std  = false
debug-logging         = 0
debuginfo-level       = 0
debuginfo-level-rustc = 0
debuginfo-level-std   = 0
debuginfo-level-tools = 0
debuginfo-level-tests = 0

[target.x86_64-apathy-linux-musl]
llvm-config           = '/opt/llvm-11.0.0/bin/llvm-config'
crt-static            = false

cc                    = 'clang'
cxx                   = 'clang++'
ar                    = 'llvm-ar'
ranlib                = 'llvm-ranlib'
linker                = 'clang'
